# Generated by Django 3.1.7 on 2021-03-24 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('трансформатор', 'трансформатор'), ('столба: 11м', 'столба: 11м'), ('столба: 9м', 'столба: 9м')], default='', max_length=250, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описания')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
