# Generated by Django 3.1.7 on 2021-03-29 14:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='количество товара')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Обшая сумма')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Обшая сумма')),
                ('owner', models.CharField(max_length=255, unique=True, verbose_name='Заказчик')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, unique=True, verbose_name='Контактный номер')),
                ('address', models.CharField(max_length=300, unique=True, verbose_name='Адресс')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='адресс почты')),
                ('bay_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_products', to='main.product', verbose_name='покупка товара')),
                ('cart_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='main.cartproduct')),
            ],
        ),
    ]
